# Path to your oh-my-zsh configuration.
ZSH=/usr/local/share/oh-my-zsh

# Theme
ZSH_THEME="lambda"

plugins=(lein debian git git-extras zsh_reload dirhistory)

source $ZSH/oh-my-zsh.sh
export QT_X11_NO_MITSHM=1
export PATH=$PATH:/apache-maven-3.8.4/bin:/apache-ant-1.10.11/bin:/rust/bin:/cargo/bin
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export DISPLAY=:0
