#!/bin/sh

docker run --privileged \
       --rm \
       -P=true \
       -p 3000:3000 \
       -p 3449:3449 \
       -p 5432:5432 \
       -p 7000:7000 \
       -p 7002:7002 \
       -p 8000:8000 \
       -p 8080:8080 \
       -p 10555:10555 \
       -e HOST_GID=`id -g` \
       -e HOST_UID=`id -u` \
       -e HOST_USER=$USER \
       -e HOST_DOCKER_GID=`getent group docker | awk -F: '{printf "%d", $3}'` \
       -v /home/$USER/.ssh:/home/$USER/.ssh \
       -v /home/$USER/src:/home/$USER/src \
       -v /home/$USER/org:/home/$USER/org \
       -v /home/$USER/.gitconfig:/home/$USER/.gitconfig \
       -v /home/$USER/.boot:/home/$USER/.boot \
       -v /home/$USER/.m2:/home/$USER/.m2 \
       -v /home/$USER/.emacs.d:/home/$USER/.emacs.d \
       -v /home/$USER/.spacemacs:/home/$USER/.spacemacs \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v /var/run/docker.sock:/var/run/docker.sock \
       -e DISPLAY=:0 \
       -it buildhost sh /root/startup.sh
