#!/bin/sh

docker run --privileged \
       --rm \
       -P=true \
       -p 3449:3449 \
       -p 8000:8000 \
       -p 8080:8080 \
       -p 10555:10555 \
       -e HOST_GID=`id -g` \
       -e HOST_UID=`id -u` \
       -e HOST_USER=$USER \
       -v /home/$USER/.ssh:/home/$USER/.ssh \
       -v /home/$USER/src:/home/$USER/src \
       -v /home/$USER/org:/home/$USER/org \
       -v /home/$USER/.gitconfig:/home/$USER/.gitconfig \
       -v /home/$USER/.boot:/home/$USER/.boot \
       -v /home/$USER/.m2:/home/$USER/.m2 \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -e DISPLAY=:0 \
       -it buildhost sh /root/startup.sh
